"""Tool to generate documentation artifacts for the repository.

- Scans python/ for modules and imports to build a module dependency graph.
- Emits Mermaid graph in docs/diagrams/module-dependency.mmd and a Markdown summary in docs/19-module-dependencies.md
- Writes a starter docs/20-documentation.md with checklist and autogenerated sections.

Usage:
    python python/tools/generate_docs.py

This script is lightweight and safe to run locally or in CI. It only reads repository files and writes to docs/.
"""
from pathlib import Path
import ast
import json

ROOT = Path(__file__).resolve().parents[3]
PY_DIR = ROOT / 'python'
DOCS_DIR = ROOT / 'docs'
DIAG_DIR = DOCS_DIR / 'diagrams'
DOCS_DIR.mkdir(parents=True, exist_ok=True)
DIAG_DIR.mkdir(parents=True, exist_ok=True)


def module_name_from_path(p: Path) -> str:
    # Convert python/foo/bar.py -> foo.bar
    rel = p.relative_to(PY_DIR)
    parts = list(rel.with_suffix('').parts)
    return '.'.join(parts)


def collect_imports():
    modules = set()
    edges = set()
    for p in PY_DIR.rglob('*.py'):
        try:
            text = p.read_text(encoding='utf-8')
        except Exception:
            text = p.read_text(errors='ignore')
        mod = module_name_from_path(p)
        modules.add(mod)
        try:
            tree = ast.parse(text)
        except Exception:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for n in node.names:
                    name = n.name.split('.')[0]
                    # map top-level import to module if present
                    for m in list(modules) + []:
                        pass
                    edges.add((mod, n.name))
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    edges.add((mod, node.module))
    return sorted(modules), sorted(edges)


def write_mermaid(modules, edges):
    # Map module names to short ids
    id_map = {m: f"m{idx}" for idx, m in enumerate(modules)}
    lines = ["flowchart TD"]
    for m in modules:
        lines.append(f"    {id_map[m]}[\"{m}\"]")
    for a, b in edges:
        # only include edges where target starts with known module root
        if any(b == m or b.startswith(m + '.') or m == b for m in modules):
            # if target not in id_map, create a node
            if b not in id_map:
                nid = f"ext{abs(hash(b)) % 100000}"
                id_map[b] = nid
                lines.append(f"    {nid}[\"{b}\"]")
            lines.append(f"    {id_map[a]} --> {id_map[b]}")
    mermaid = '\n'.join(lines) + '\n'
    (DIAG_DIR / 'module-dependency.mmd').write_text(mermaid, encoding='utf-8')
    return mermaid


def write_module_doc(modules, edges, mermaid):
    md = []
    md.append('# 第十九部分 — 模块依赖说明')
    md.append('')
    md.append('自动生成：模块依赖关系与调用概览（按文件扫描 imports）')
    md.append('')
    md.append('## 模块列表')
    md.append('')
    for m in modules:
        md.append(f'- `{m}`')
    md.append('')
    md.append('## 依赖关系（Mermaid）')
    md.append('')
    md.append('```mermaid')
    md.append(mermaid)
    md.append('```')
    md.append('')
    md.append('## 调用关系（静态分析提醒）')
    md.append('此处为静态 import 扫描得到的依赖关系。函数级别的调用/数据流需要运行时分析或更复杂的静态分析工具（例如 pyan、snakefood 或使用 AST + type inference）。')
    md.append('')
    md.append('## 参数说明')
    md.append('请参考 `config/parameters.yaml` 和 `config/param_grid_example.yaml`。可以将这些 YAML 转换为 Markdown 表格以生成参数文档。')
    md.append('')
    md.append('## 生成脚本')
    md.append('运行 `python python/tools/generate_docs.py` 将重新生成此页面和 Mermaid 图。')

    (DOCS_DIR / '19-module-dependencies.md').write_text('\n'.join(md), encoding='utf-8')


def write_documentation_index():
    md = []
    md.append('# 第二十部分 — 文档')
    md.append('')
    md.append('自动生成的文档骨架（README / 安装 / 升级 / 参数 / 开发 / 版本日志 / FAQ）')
    md.append('')
    md.append('## README.md (自动/手动合并建议)')
    md.append('仓库根已有 README.md，可以将下列信息补充进去：安装、快速使用、配置示例、常见问题。')
    md.append('')
    md.append('## 安装说明')
    md.append('示例：')
    md.append('```bash')
    md.append('python -m pip install -r requirements-dev.txt')
    md.append('python -m pip install .')
    md.append('```')
    md.append('')
    md.append('## 升级说明')
    md.append('- 如果使用 pip 安装，升级可以使用 `pip install --upgrade <package>` 或通过重新构建 wheel 并安装。')
    md.append('')
    md.append('## 参数说明')
    md.append('- 请参考 `config/parameters.yaml`。可以使用脚本将 YAML 中的字段和默认值导出为 Markdown 表格。')
    md.append('')
    md.append('## 开发说明')
    md.append('- 运行测试： `python python/tools/test_runner.py`')
    md.append('- 本地环境：推荐 Python 3.10（见 pyproject.toml）')
    md.append('')
    md.append('## 版本日志')
    md.append('- 建议使用 Conventional Commits / changelog 工具自动生成。')
    md.append('')
    md.append('## FAQ')
    md.append('- 将常见问题与解决步骤列在此处。')

    (DOCS_DIR / '20-documentation.md').write_text('\n'.join(md), encoding='utf-8')


if __name__ == '__main__':
    modules, edges = collect_imports()
    mermaid = write_mermaid(modules, edges)
    write_module_doc(modules, edges, mermaid)
    write_documentation_index()
    print('Generated docs/19-module-dependencies.md, docs/20-documentation.md and diagrams')
